### PR TITLE
Fix panoramix lint errors

### LINKED ISSUE #37: Fix golint error

### PR DESCRIPTION
**Pull request by 0xpanoramix**
Signed-off-by: Luca Georges Francois <luca.georges-francois@epitech.eu>

# Description

This PR fixes panoramix's lint errors.
It fixes #37 .

# Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [X] I have added sufficient documentation in the code

### CODE REVIEW

File: obelix/panoramix/services/google/client.go [hunk 1]
```diff
@@ -10,16 +10,16 @@ import (
...
 )
 
 // TODO : Must be removed when the credentials API is up.
 func init() {
-	ClientId = os.Getenv("GOOGLE_CLIENT_ID")
+	ClientID = os.Getenv("GOOGLE_CLIENT_ID")
 	ClientSecret = os.Getenv("GOOGLE_CLIENT_SECRET")
-	RedirectUrl = os.Getenv("GOOGLE_REDIRECT_URL")
+	RedirectURL = os.Getenv("GOOGLE_REDIRECT_URL")
 }
```
Comment (Cleopha) [inline obelix/panoramix/services/google/client.go:24]: Please check if variable is not set

**Review by Cleopha — CHANGES_REQUESTED** [review]
Looks good for me just some little comment

File: obelix/panoramix/services/google/client.go (hunk 1 above)
Comment (0xpanoramix) [reply obelix/panoramix/services/google/client.go:24]: It's only here for dev. purposes, as you can see below there's a TODO to remove this :)

**Review by Cleopha — APPROVED** [review]
